spring.application.name=chatop

server.port=3001

logging.level.root=ERROR
logging.level.com.chatop=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# logging.level.org.springframework.security=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${DB_URL_CHATOP}
spring.datasource.username=${DB_USERNAME_CHATOP}
spring.datasource.password=${DB_PASSWORD_CHATOP}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# logging.level.org.springframework.jdbc=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET_CHATOP}

app.images.base-url=http://localhost:3001/api/images/
app.images.dir=${IMAGES_DIR_CHATOP}


# access swagger at http://localhost:3001/swagger-ui/index.html