spring.application.name=chatop

server.port=3001

logging.level.root=ERROR
logging.level.com.chatop=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

spring.datasource.url=jdbc:mysql://localhost:3306/chatop_db
spring.datasource.username=chatop
spring.datasource.password=.O+Q7a!Eh@lPrA&{ho?dGR*Wg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=1m2;t#e(s89tghdS{@efgeKc^d,r-etKU,frseTryeyMMDlF99883o%rJFKls9009;

app.images.base-url=http://localhost:3001/api/images/
app.images.dir= E:/img-chatop/img

